---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: localhost:5000/staffing-backend
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/staffing_process
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
              value: oauth2-staffing-process-client
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE
              value: client_credentials
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://keycloak:8080/realms/staffing-process-ui-realm
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI # Needed??
              value: http://keycloak:8080/realms/staffing-process-ui-realm/protocol/openid-connect/certs
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
              value: http://keycloak:8080/realms/staffing-process-ui-realm/protocol/openid-connect/token
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/staffing-process-ui-realm
            - name: KEYCLOAK_PUBLIC_CLIENT
              value: "false"
            - name: KEYCLOAK_ENABLE_CORS
              value: "true"
            - name: KEYCLOAK_BEARER_ONLY
              value: "true"
            - name: KEYCLOAK_SSL_REQUIRED
              value: external
            - name: KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS
              value: "true"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: LOKI_HOST
              value: http://loki:3100
            - name: APP_SECURITY_TOKEN
              value: dev-token
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"              
          ports:
            - containerPort: 8080
            - containerPort: 5005
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: X-APP-TOKEN
                  value: dev-token
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32700
      name: http
    - port: 5005
      targetPort: 5005
      nodePort: 32005
      name: debug
---