# core-services.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: local/staffing
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 30 && curl -X POST http://localhost:8080/actuator/refresh"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/staffing_process"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "pass"
  SPRING_LIQUIBASE_ENABLED: "true"  # For DB schema management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: local/staffing-ui
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  API_BASE_URL: "/backend"
  KEYCLOAK_URL: "/keycloak"