# db-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:latest
        command: ["sh", "-c", "mysql -h db -uroot -ppass staffing_process < /scripts/init.sql"]
        volumeMounts:
          - name: init-script
            mountPath: /scripts
      volumes:
        - name: init-script
          configMap:
            name: db-init-script
      restartPolicy: Never
  backoffLimit: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS staffing_process;
    USE staffing_process;
    -- Your schema initialization here