# expose-services.yaml
# ──────────────────────────────────────────────────────────
# Services of type NodePort to expose selected apps on host
# ──────────────────────────────────────────────────────────

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-app
# spec:
#   type: NodePort
#   selector:
#     app: backend-app
#   ports:
#     - name: http
#       port: 8080
#       targetPort: 8080
#       nodePort: 30080

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-app
# spec:
#   type: NodePort
#   selector:
#     app: frontend-app
#   ports:
#     - name: http
#       port: 4200
#       targetPort: 4200
#       nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30088

---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090

