# keycloak.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.1
        args: ["start-dev", "--import-realm"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: realm-config
          mountPath: /opt/keycloak/data/import
      volumes:
      - name: realm-config
        configMap:
          name: keycloak-realm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
data:
  realm-import.json: |
    {
      "realm": "staffing-process-ui-realm",
      "enabled": true
      // Your full realm config here
    }